### PR TITLE
Gummer CSS homework2

### PR DESCRIPTION
**Pull request by gummer11**
Added 5 CSS exercise.

### CODE REVIEW

**Comment by gummer11** [comment]
Hi Virag, it was a long time ago the last homework, i am happy to make a new one. :)

**Comment by virag-ky** [comment]
Hi @gummer11 , I'm happy you did the homework 😃 

Some feedback:
- for the widths (200px) you used 120px but it's not a big deal, it's okay to define your own widths
- in exercise 5 you forgot to wrap the flex items (they should wrap when the flex container shrinks and when there's no more space for the flex items)

**Comment by virag-ky** [comment]
I found it 😃 Thank you for the changes, great work and I'm happy that you are consistent with the homework 👍🏻

**Comment by gummer11** [comment]
I am happy to make the homework, because i can practise! You are getting near the 100 day challenge, keep going, not too far! 👍

**Pull request merged**
